### ISSUE TITLE
crackmapexec incompatibility

### ISSUE THREAD

**Issue by purim-sudo** [champmq/TheScrapper#6]
crackmapexec 5.4.0 requires pypsrp<0.8.0,>=0.7.0, but you have pypsrp 0.8.1 which is incompatible. it seems its incompatible with new versions would you try to solve this issue?to be compatible with new versions

**Comment by champmq** [comment]
Just to make it clear do u still need help with this or is it alright now?

**Comment by purim-sudo** [comment]
Yeah I still need helpit isnt compatible with the new version and brings
that error report

**Comment by champmq** [comment]
Ill check it out and will msg u when its fixed

**Comment by champmq** [comment]
Okay so I tried to recreate ur error but idk how u did it so I need the steps u r doing bcs its working just fine for me

**Comment by purim-sudo** [comment]
please have you tried it in the new latest kali linux?when i install  the
tool and try reinstalling its dependencies, thats where the error message
comes about...since the new version seems not to support it creating a
message that it may misbehave

**Comment by champmq** [comment]
I tried it on windows dont have any device that has kali on it rn but I am pretty sure that it should work

**Comment by purim-sudo** [comment]
Installing collected packages: argparse, beautifulsoup4, socid-extractor
  WARNING: The script socid_extractor is installed in
'/home/purim/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this
warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all
the packages that are installed. This behaviour is the source of the
following dependency conflicts.
crackmapexec 5.4.0 requires aioconsole<0.4.0,>=0.3.3, but you have
aioconsole 0.3.1 which is incompatible.
crackmapexec 5.4.0 requires beautifulsoup4<5,>=4.11, but you have
beautifulsoup4 4.10.0 which is incompatible.
crackmapexec 5.4.0 requires minikerberos==0.3.3, but you have minikerberos
0.4.0 which is incompatible.
crackmapexec 5.4.0 requires neo4j<5.0.0,>=4.1.1, but you have neo4j
5.2.dev0 which is incompatible.
crackmapexec 5.4.0 requires pypsrp<0.8.0,>=0.7.0, but you have pypsrp 0.8.1
which is incompatible.
crackmapexec 5.4.0 requires xmltodict<0.13.0,>=0.12.0, but you have
xmltodict 0.13.0 which is incompatible.
Successfully installed argparse-1.4.0 beautifulsoup4-4.10.0
socid-extractor-0.0.23

this is the error message

**Comment by champmq** [comment]
This is a problem from "socid-extractor" so I cant rly help with that
