### ISSUE TITLE
new to code. installed the requirments.txt. closing automatically when opened.

### ISSUE THREAD

**Issue by 00anonymous11** [champmq/TheScrapper#7]
hey i'm knew to git hub and code in general so i didn't know how to dm, but i wanted to ask how to run the code. it closes immediately when i open it with python. i installed the requirements.txt files too. i'm A noob sorry.

**Comment by champmq** [comment]
How do u run the file? And r u on windows or linux?

**Comment by champmq** [comment]
Okay so I am pretty sure u r not giving it any arguments maybe read the readme it explains how to use it if u have questions after that lmk
