### ISSUE TITLE
Wrong logic in URL check 

### ISSUE THREAD

**Issue by StasyaPion** [champmq/TheScrapper#8]
Hi there! First, thank you for sharing your project, it's awesome! 

I noticed an incorrect URL check in the file: 
https://github.com/champmq/TheScrapper/blob/main/TheScrapper.py
**line 60** 

```
if target_type == "URL":
    if "https://" not in args.url or "http://" not in args.url: 
        args.url = "https://" + args.url 
```

Imagine I have `http://example.com`

Due to your code, the IF statement will return True if at least 1 condition is True (because of using OR).
The `"https://" not in args.url` is True
The `"http://" not in args.url` is False
So for the URL `http://example.com` I will have `https:// + http://example.com`

I recommend to fix your code: 
```
if target_type == "URL":
    if not (args.url.startswith("https://") or args.url.startswith("http://")):
        args.url = "http://" + args.url
```
In this situation for `http://example.com`
The `args.url.startswith("https://") or args.url.startswith("http://")` is True
So I will have `http://example.com ` to scan 

I'm using `"http://" + args.url` Because sometimes I get `requests.exceptions.SSLError` when server expects HTTP connection and I'm using https:// instead

**Comment by champmq** [comment]
Hi, Ive never noticed that but ur explanation was very helpful ty for that and for opening the issue I will fix it asap.
